[build]
  command = "npm install --legacy-peer-deps"
  publish = "public"
  functions = "functions"

[functions]
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
